
name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - uses: actions/checkout@v2.0.0

    - name: Get all tags
      run: git fetch --prune --unshallow --tags

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn ci
